### ISSUE TITLE
Consulta al main.py

### ISSUE THREAD

**Issue by ejdecena** [laar19/blockchain-concepcion#1]
Hola Luís. Interesante tu código sobre blockchain.
En el archivo **main.py** defines una clase "Block" y varias funciones asociadas a las operaciones típicas de una blockchain. Sin embargo, mi pregunta es: ¿por qué no creaste un archivo **blockchain.py** conteniendo una clase **Blockchain** con todas estas funciones incorporadas como **métodos** a esta clase? Hay que seguir la nomenclatura de los nombres de clase y de archivo de Python (PEP8).

Podríamos crear un repositorio para ir trabajando sobre estas ideas :)

**Comment by ejdecena** [comment]
También habría que explicar un poco qué significa cada parámetro en el código, añadiendo **docstrings** a los métodos y clases. Del mismo modo, en el **README.md** debería hacerse una pequeña reseña de lo que es una Blockchain y de cómo funciona, para que podamos asociar lo teórico con tu código.

**Comment by laar19** [comment]
Totalmente aceptadas las sugerencias. En su momento lo implementé de esa manera porque fue la primera idea que se me vino a la cabeza y no lo pulí más. Voy a investigar también sobre los __docstrings__ para echarles un ojo. Me interesa la idea sobre el repositorio

**Comment by ejdecena** [comment]
Si no sabes lo de docstring debes aprenderlo lo antes posible. Pythonista
que se respete lo aprende entre las primeras cosas, jejeje...

Si gustas créate un nuevo repositorio llamado blockchain y ahí empezamos de
cero.

También recuerda colaborarme cuando puedas con el 01_lenguaje_python.ipnb
en mi repo please.

Seguimos en contacto.

**Comment by ejdecena** [comment]
Si no sabes lo de **docstring** debes aprenderlo lo antes posible. Pythonista
que se respete lo aprende entre las primeras cosas, jejeje...

Si gustas créate un nuevo repositorio llamado *blockchain* y ahí empezamos de cero.

También recuerda colaborarme cuando puedas con el [**01_lenguaje_python.ipynb**](https://github.com/ejdecena/herramientas_python/blob/master/01_lenguaje_python.ipynb) en mi repo please.

Seguimos en contacto.

**Comment by laar19** [comment]
En cuanto tenga el chance lo veo .Se mejoró un poco el código de la blockchain

**Comment by ejdecena** [comment]
Muy bien, resuelto.
